version: '3'
services:
  api:
    restart: always
    build: .
    ports:
     - "9000:9000"
     - "5858:5858"
    env_file:
     - variables.env
    environment:
     - NODE_ENV=development
    volumes:
     - .:/usr/src/app
    depends_on: 
     - redis
    entrypoint: ["npm", "start"]
  redis:
    image: "redis:alpine"