version: '3'
services:
  api:
    restart: always
    build: .
    ports:
     - "9000:9000"
    environment: 
     - SENDGRID_KEY=${SENDGRID_KEY}
     - MASTER_KEY=${MASTER_KEY}
     - JWT_SECRET=${JWT_SECRET}
     - NODE_ENV=production
    volumes:
     - .:/usr/src/app
    depends_on: 
     - redis
    entrypoint: ["node", "./src"]
  redis:
    image: "redis:alpine"