#!/bin/bash
echo "setting env variables"

ENV_BROWSER_HYDRA_HOST=localhost
ENV_BROWSER_CONSUMER_HOST=localhost
ENV_BROWSER_IDP_HOST=localhost
ENV_BROWSER_OATHKEEPER_PROXY_HOST=localhost
ENV_HYDRA_VERSION=v1.0.0-beta.9
ENV_OATHKEEPER_VESRION=v0.13.9_oryOS.9
ENV_KETO_VERSION=v0.1.9-sandbox_oryOS.9

## sensitive info
export HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
export SENDGRID_KEY=SEND_GRID_API_KEY
export MASTER_KEY=ak6b2hzWgsUwf13nMB6HB23ILMgOo5P8
export JWT_SECRET=21r4YUIDuKOJrYKAzG6zkxebfaYP7aNM
export SYSTEM_SECRET=youReallyNeedToChangeThis
export POSTGRES_USER=dbuser
export POSTGRES_PASSWORD=secret
export POSTGRES_DB=accesscontroldb
export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgresd:5432/$POSTGRES_DB?sslmode=disable
##

export LOGIN_CONSENT_VERSION=$ENV_HYDRA_VERSION
export HYDRA_VERSION=$ENV_HYDRA_VERSION
export OATHKEEPER_VERSION=$ENV_OATHKEEPER_VESRION
export KETO_VERSION=$ENV_KETO_VERSION

echo "HYDRA_VERSION: " $HYDRA_VERSION

export BROWSER_HYDRA_HOST=$ENV_BROWSER_HYDRA_HOST
export BROWSER_CONSUMER_HOST=$ENV_BROWSER_CONSUMER_HOST
export BROWSER_IDP_HOST=$ENV_BROWSER_IDP_HOST
export BROWSER_OATHKEEPER_PROXY_HOST=$ENV_BROWSER_OATHKEEPER_PROXY_HOST

export OAUTH2_CONSENT_URL=http://$BROWSER_IDP_HOST:4488/consent
export OAUTH2_LOGIN_URL=http://$BROWSER_IDP_HOST:4488/login
export OAUTH2_ISSUER_URL=http://$BROWSER_HYDRA_HOST:4444
export HYDRA_ADMIN_URL=http://hydra:4445
export NODE_TLS_REJECT_UNAUTHORIZED=1

export OAUTH2_SHARE_ERROR_DEBUG=1