#!/bin/bash
echo "setting env variables"

## hosts
ENV_HYDRA_HOST=localhost
ENV_CONSUMER_HOST=localhost
ENV_IDP_HOST=localhost
ENV_OATHKEEPER_PROXY_HOST=localhost
ENV_PJ_OAUTH_CLIENT_HOST=localhost

## ports
IDP_PORT=9000
HYDRA_PUBLIC_PORT=4444
HYDRA_ADMIN_PORT=4445
POSTGRES_DB_PORT=5432
PJ_OAUTH_CLIENT_PORT=4000

## versions
ENV_HYDRA_VERSION=v1.0.0-beta.9
ENV_OATHKEEPER_VESRION=v0.13.9_oryOS.9
ENV_KETO_VERSION=v0.1.9-sandbox_oryOS.9

## sensitive info
export HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
export SENDGRID_KEY=SEND_GRID_API_KEY
export MASTER_KEY=ak6b2hzWgsUwf13nMB6HB23ILMgOo5P8
export JWT_SECRET=21r4YUIDuKOJrYKAzG6zkxebfaYP7aNM
export SYSTEM_SECRET=youReallyNeedToChangeThis
export POSTGRES_USER=dbuser
export POSTGRES_PASSWORD=secret
export POSTGRES_DB=accesscontroldb
export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgresd:$POSTGRES_DB_PORT/$POSTGRES_DB?sslmode=disable
export PJ_OAUTH_CLIENT_ID=pajuani_oauth_client
export PJ_OAUTH_CLIENT_SECRET=youReallyNeedToChangeThis
##

export LOGIN_CONSENT_VERSION=$ENV_HYDRA_VERSION
export HYDRA_VERSION=$ENV_HYDRA_VERSION
export OATHKEEPER_VERSION=$ENV_OATHKEEPER_VESRION
export KETO_VERSION=$ENV_KETO_VERSION

echo "HYDRA_VERSION: " $HYDRA_VERSION

export HYDRA_HOST=$ENV_HYDRA_HOST
export CONSUMER_HOST=$ENV_CONSUMER_HOST
export IDP_HOST=$ENV_IDP_HOST
export OATHKEEPER_PROXY_HOST=$ENV_OATHKEEPER_PROXY_HOST

export OAUTH2_CONSENT_URL=http://$IDP_HOST:$IDP_PORT/consent
export OAUTH2_LOGIN_URL=http://$IDP_HOST:$IDP_PORT/login
export OAUTH2_ISSUER_URL=http://$HYDRA_HOST:$HYDRA_PUBLIC_PORT
export HYDRA_ADMIN_URL=http://hydra:$HYDRA_ADMIN_PORT
export PJ_OAUTH_CLIENT_CALLBACK_URL=http://$ENV_PJ_OAUTH_CLIENT_HOST:$ENV_PJ_OAUTH_CLIENT_HOST/callback
export NODE_TLS_REJECT_UNAUTHORIZED=1

export OAUTH2_SHARE_ERROR_DEBUG=1